# Replace

In [19]:
import pandas as pd

var =pd.read_csv("C:\\Users\\Harsh Verma\\Documents\\Panda\\stock_data.csv")
var

,NO.,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOL,CHANGE %
0,1,ELECTTHERM,Electrotherm (India) Limited,473907,9457,50.11000
1,2,NBIFIN,N. B. I. Industrial Finance Com.,5754,154,37.22500
2,3,HINDCON,Hindcon Chemicals Limited,304759,9248,32.95345
3,4,GKWLIMITED,GKW Limited,21375,711,30.04920
4,5,21STCENMGM,21st Century Management Serv.,110375,3879,31.04920
5,6,ALPHAGEO,Alphageo (India) Limited,1,8356,87.85261
6,7,UNIENTER,Uniphos Enterprises Limited,1,8357,21.52800
7,8,JAGSNPHARM,Jagsonpal Pharmaceuticals Lim.,1,7314,87.10140
8,9,SKMEGGPROD,SKM Egg Products Export (India) Lim.,1,8777,18.80412
9,10,SWELECTES,Swelect Energy Systems Limited,1,1943,18.98730
10,11,NAHARPOLY,Nahar Poly Films Limited,38574,3155,15.55583
11,12,PODDARHOUS,Poddar Housing and Development,1,3012,25.88360
12,13,LINC,Linc Limited,60551,4076,14.85367
13,14,LINC123,Linc Limited123,60550,4075,15.85367

In [3]:
var.replace(to_replace=1,value=22)

,NO.,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOL,CHANGE %
0,22,ELECTTHERM,Electrotherm (India) Limited,473907,9457,50.11000
1,2,NBIFIN,N. B. I. Industrial Finance Com.,5754,154,37.22500
2,3,HINDCON,Hindcon Chemicals Limited,304759,9248,32.95345
3,4,GKWLIMITED,GKW Limited,21375,711,30.04920
4,5,21STCENMGM,21st Century Management Serv.,110375,3879,31.04920
5,6,ALPHAGEO,Alphageo (India) Limited,22,8356,87.85261
6,7,UNIENTER,Uniphos Enterprises Limited,22,8357,21.52800
7,8,JAGSNPHARM,Jagsonpal Pharmaceuticals Lim.,22,7314,87.10140
8,9,SKMEGGPROD,SKM Egg Products Export (India) Lim.,22,8777,18.80412
9,10,SWELECTES,Swelect Energy Systems Limited,22,1943,18.98730
10,11,NAHARPOLY,Nahar Poly Films Limited,38574,3155,15.55583
11,12,PODDARHOUS,Poddar Housing and Development,22,3012,25.88360
12,13,LINC,Linc Limited,60551,4076,14.85367
13,14,LINC123,Linc Limited123,60550,4075,15.85367

In [7]:
 var.replace(to_replace="ELECTTHERM",value=" sapna dekhna acchi baat hai")

,NO.,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOL,CHANGE %
0,1,sapna dekhna acchi baat hai,Electrotherm (India) Limited,473907,9457,50.11000
1,2,NBIFIN,N. B. I. Industrial Finance Com.,5754,154,37.22500
2,3,HINDCON,Hindcon Chemicals Limited,304759,9248,32.95345
3,4,GKWLIMITED,GKW Limited,21375,711,30.04920
4,5,21STCENMGM,21st Century Management Serv.,110375,3879,31.04920
5,6,ALPHAGEO,Alphageo (India) Limited,1,8356,87.85261
6,7,UNIENTER,Uniphos Enterprises Limited,1,8357,21.52800
7,8,JAGSNPHARM,Jagsonpal Pharmaceuticals Lim.,1,7314,87.10140
8,9,SKMEGGPROD,SKM Egg Products Export (India) Lim.,1,8777,18.80412
9,10,SWELECTES,Swelect Energy Systems Limited,1,1943,18.98730
10,11,NAHARPOLY,Nahar Poly Films Limited,38574,3155,15.55583
11,12,PODDARHOUS,Poddar Housing and Development,1,3012,25.88360
12,13,LINC,Linc Limited,60551,4076,14.85367
13,14,LINC123,Linc Limited123,60550,4075,15.85367

In [ ]:
var.replace([1,2,3,4,5,6,7,8,9],39)

In [10]:
var.replace("[A-Z]","PnP",regex=True)

,NO.,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOL,CHANGE %
0,1,PnPPnPPnPPnPPnPPnPPnPPnPPnPPnP,PnPlectrotherm (PnPndia) PnPimited,473907,9457,50.11000
1,2,PnPPnPPnPPnPPnPPnP,PnP. PnP. PnP. PnPndustrial PnPinance PnPom.,5754,154,37.22500
2,3,PnPPnPPnPPnPPnPPnPPnP,PnPindcon PnPhemicals PnPimited,304759,9248,32.95345
3,4,PnPPnPPnPPnPPnPPnPPnPPnPPnPPnP,PnPPnPPnP PnPimited,21375,711,30.04920
4,5,21PnPPnPPnPPnPPnPPnPPnPPnP,21st PnPentury PnPanagement PnPerv.,110375,3879,31.04920
5,6,PnPPnPPnPPnPPnPPnPPnPPnP,PnPlphageo (PnPndia) PnPimited,1,8356,87.85261
6,7,PnPPnPPnPPnPPnPPnPPnPPnP,PnPniphos PnPnterprises PnPimited,1,8357,21.52800
7,8,PnPPnPPnPPnPPnPPnPPnPPnPPnPPnP,PnPagsonpal PnPharmaceuticals PnPim.,1,7314,87.10140
8,9,PnPPnPPnPPnPPnPPnPPnPPnPPnPPnP,PnPPnPPnP PnPgg PnProducts PnPxport (PnPndia) ...,1,8777,18.80412
9,10,PnPPnPPnPPnPPnPPnPPnPPnPPnP,PnPwelect PnPnergy PnPystems PnPimited,1,1943,18.98730
10,11,PnPPnPPnPPnPPnPPnPPnPPnPPnP,PnPahar PnPoly PnPilms PnPimited,38574,3155,15.55583
11,12,PnPPnPPnPPnPPnPPnPPnPPnPPnPPnP,PnPoddar PnPousing and PnPevelopment,1,3012,25.88360
12,13,PnPPnPPnPPnP,PnPinc PnPimited,60551,4076,14.85367
13,14,PnPPnPPnPPnP123,PnPinc PnPimited123,60550,4075,15.85367

# Using Dictonary

In [11]:
var.replace({"SYMBOL":'[A-Z]'},22,regex=True)

C:\Users\Harsh Verma\AppData\Local\Temp\ipykernel_1396\1996798884.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  var.replace({"SYMBOL":'[A-Z]'},22,regex=True)

,NO.,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOL,CHANGE %
0,1,22,Electrotherm (India) Limited,473907,9457,50.11000
1,2,22,N. B. I. Industrial Finance Com.,5754,154,37.22500
2,3,22,Hindcon Chemicals Limited,304759,9248,32.95345
3,4,22,GKW Limited,21375,711,30.04920
4,5,22,21st Century Management Serv.,110375,3879,31.04920
5,6,22,Alphageo (India) Limited,1,8356,87.85261
6,7,22,Uniphos Enterprises Limited,1,8357,21.52800
7,8,22,Jagsonpal Pharmaceuticals Lim.,1,7314,87.10140
8,9,22,SKM Egg Products Export (India) Lim.,1,8777,18.80412
9,10,22,Swelect Energy Systems Limited,1,1943,18.98730
10,11,22,Nahar Poly Films Limited,38574,3155,15.55583
11,12,22,Poddar Housing and Development,1,3012,25.88360
12,13,22,Linc Limited,60551,4076,14.85367
13,14,22,Linc Limited123,60550,4075,15.85367

In [13]:
var.replace(1,method="bfill")

C:\Users\Harsh Verma\AppData\Local\Temp\ipykernel_1396\1975081475.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  var.replace(1,method="bfill")

,NO.,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOL,CHANGE %
0,2,ELECTTHERM,Electrotherm (India) Limited,473907,9457,50.11000
1,2,NBIFIN,N. B. I. Industrial Finance Com.,5754,154,37.22500
2,3,HINDCON,Hindcon Chemicals Limited,304759,9248,32.95345
3,4,GKWLIMITED,GKW Limited,21375,711,30.04920
4,5,21STCENMGM,21st Century Management Serv.,110375,3879,31.04920
5,6,ALPHAGEO,Alphageo (India) Limited,38574,8356,87.85261
6,7,UNIENTER,Uniphos Enterprises Limited,38574,8357,21.52800
7,8,JAGSNPHARM,Jagsonpal Pharmaceuticals Lim.,38574,7314,87.10140
8,9,SKMEGGPROD,SKM Egg Products Export (India) Lim.,38574,8777,18.80412
9,10,SWELECTES,Swelect Energy Systems Limited,38574,1943,18.98730
10,11,NAHARPOLY,Nahar Poly Films Limited,38574,3155,15.55583
11,12,PODDARHOUS,Poddar Housing and Development,60551,3012,25.88360
12,13,LINC,Linc Limited,60551,4076,14.85367
13,14,LINC123,Linc Limited123,60550,4075,15.85367

In [15]:
var.replace(1,method="ffill",limit=3)

C:\Users\Harsh Verma\AppData\Local\Temp\ipykernel_1396\271419978.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  var.replace(1,method="ffill",limit=3)

,NO.,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOL,CHANGE %
0,1,ELECTTHERM,Electrotherm (India) Limited,473907,9457,50.11000
1,2,NBIFIN,N. B. I. Industrial Finance Com.,5754,154,37.22500
2,3,HINDCON,Hindcon Chemicals Limited,304759,9248,32.95345
3,4,GKWLIMITED,GKW Limited,21375,711,30.04920
4,5,21STCENMGM,21st Century Management Serv.,110375,3879,31.04920
5,6,ALPHAGEO,Alphageo (India) Limited,110375,8356,87.85261
6,7,UNIENTER,Uniphos Enterprises Limited,110375,8357,21.52800
7,8,JAGSNPHARM,Jagsonpal Pharmaceuticals Lim.,110375,7314,87.10140
8,9,SKMEGGPROD,SKM Egg Products Export (India) Lim.,1,8777,18.80412
9,10,SWELECTES,Swelect Energy Systems Limited,1,1943,18.98730
10,11,NAHARPOLY,Nahar Poly Films Limited,38574,3155,15.55583
11,12,PODDARHOUS,Poddar Housing and Development,38574,3012,25.88360
12,13,LINC,Linc Limited,60551,4076,14.85367
13,14,LINC123,Linc Limited123,60550,4075,15.85367

In [20]:
var.replace(1,method="ffill",limit=3,inplace=True)
var

C:\Users\Harsh Verma\AppData\Local\Temp\ipykernel_1396\3407534592.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  var.replace(1,method="ffill",limit=3,inplace=True)

,NO.,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOL,CHANGE %
0,1,ELECTTHERM,Electrotherm (India) Limited,473907,9457,50.11000
1,2,NBIFIN,N. B. I. Industrial Finance Com.,5754,154,37.22500
2,3,HINDCON,Hindcon Chemicals Limited,304759,9248,32.95345
3,4,GKWLIMITED,GKW Limited,21375,711,30.04920
4,5,21STCENMGM,21st Century Management Serv.,110375,3879,31.04920
5,6,ALPHAGEO,Alphageo (India) Limited,110375,8356,87.85261
6,7,UNIENTER,Uniphos Enterprises Limited,110375,8357,21.52800
7,8,JAGSNPHARM,Jagsonpal Pharmaceuticals Lim.,110375,7314,87.10140
8,9,SKMEGGPROD,SKM Egg Products Export (India) Lim.,1,8777,18.80412
9,10,SWELECTES,Swelect Energy Systems Limited,1,1943,18.98730
10,11,NAHARPOLY,Nahar Poly Films Limited,38574,3155,15.55583
11,12,PODDARHOUS,Poddar Housing and Development,38574,3012,25.88360
12,13,LINC,Linc Limited,60551,4076,14.85367
13,14,LINC123,Linc Limited123,60550,4075,15.85367