# Read csv

In [28]:
import pandas as pd

csv_1=pd.read_csv("C:\\Users\\Harsh Verma\\Documents\\Panda\\annual.csv")
csv_1

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H01,Total income,Financial performance,54462,ANZSIC06 division A
1,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H04,Sales of goods and services,Financial performance,51472,ANZSIC06 division A
2,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H05,"Interest, dividends and donations",Financial performance,893,ANZSIC06 division A
3,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H06,"Government funding, grants and subsidies",Financial performance,15,ANZSIC06 division A
4,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H07,Non-operating income,Financial performance,2081,ANZSIC06 division A
...,...,...,...,...,...,...,...,...,...,...
93,2023,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H05,"Interest, dividends and donations",Financial performance,222,ANZSIC06 groups A014 and A015
94,2023,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H07,Non-operating income,Financial performance,680,ANZSIC06 groups A014 and A015
95,2023,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H08,Total expenditure,Financial performance,11627,ANZSIC06 groups A014 and A015
96,2023,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H09,Interest and donations,Financial performance,910,ANZSIC06 groups A014 and A015
97,2023,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H10,Indirect taxes,Financial performance,204,ANZSIC06 groups A014 and A015

In [29]:
csv_2=pd.read_csv("C:\\Users\\Harsh Verma\\Documents\\Panda\\annual.csv",nrows=2)
csv_2

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H01,Total income,Financial performance,54462,ANZSIC06 division A
1,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H04,Sales of goods and services,Financial performance,51472,ANZSIC06 division A

In [15]:
csv_3=pd.read_csv("C:\\Users\\Harsh Verma\\Documents\\Panda\\annual.csv",usecols=[0,6],skiprows=[0,1,3,4])
csv_3

    2023        Sales of goods and services
0   2023               Non-operating income
1   2023                  Total expenditure
2   2023             Interest and donations
3   2023                     Indirect taxes
4   2023                       Depreciation
..   ...                                ...
89  2023  Interest, dividends and donations
90  2023               Non-operating income
91  2023                  Total expenditure
92  2023             Interest and donations
93  2023                     Indirect taxes

[94 rows x 2 columns]

# Changing index or Header to another rows

###### csv_4=pd.read_csv("C:\\Users\\Harsh Verma\\Documents\\Panda\\annual.csv",index_col="Industry_name_NZSIOC")
csv_4

In [30]:
csv_5=pd.read_csv("C:\\Users\\Harsh Verma\\Documents\\Panda\\annual.csv",header=2)
csv_5

,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H04,Sales of goods and services,Financial performance,51472,ANZSIC06 division A
0,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H05,"Interest, dividends and donations",Financial performance,893,ANZSIC06 division A
1,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H06,"Government funding, grants and subsidies",Financial performance,15,ANZSIC06 division A
2,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H07,Non-operating income,Financial performance,2081,ANZSIC06 division A
3,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H08,Total expenditure,Financial performance,48377,ANZSIC06 division A
4,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H09,Interest and donations,Financial performance,3641,ANZSIC06 division A
...,...,...,...,...,...,...,...,...,...,...
91,2023,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H05,"Interest, dividends and donations",Financial performance,222,ANZSIC06 groups A014 and A015
92,2023,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H07,Non-operating income,Financial performance,680,ANZSIC06 groups A014 and A015
93,2023,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H08,Total expenditure,Financial performance,11627,ANZSIC06 groups A014 and A015
94,2023,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H09,Interest and donations,Financial performance,910,ANZSIC06 groups A014 and A015
95,2023,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H10,Indirect taxes,Financial performance,204,ANZSIC06 groups A014 and A015

In [43]:
csv_6=pd.read_csv("C:\\Users\\Harsh Verma\\Documents\\Panda\\annual.csv",names=["col","col_1","col_2","col_3","col_4","col_5","col_6","col_7","col_8","col_9"])
csv_6

,col,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9
0,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
1,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H01,Total income,Financial performance,54462,ANZSIC06 division A
2,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H04,Sales of goods and services,Financial performance,51472,ANZSIC06 division A
3,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H05,"Interest, dividends and donations",Financial performance,893,ANZSIC06 division A
4,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H06,"Government funding, grants and subsidies",Financial performance,15,ANZSIC06 division A
...,...,...,...,...,...,...,...,...,...,...
94,2023,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H05,"Interest, dividends and donations",Financial performance,222,ANZSIC06 groups A014 and A015
95,2023,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H07,Non-operating income,Financial performance,680,ANZSIC06 groups A014 and A015
96,2023,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H08,Total expenditure,Financial performance,11627,ANZSIC06 groups A014 and A015
97,2023,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H09,Interest and donations,Financial performance,910,ANZSIC06 groups A014 and A015
98,2023,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H10,Indirect taxes,Financial performance,204,ANZSIC06 groups A014 and A015

In [45]:
csv_7=pd.read_csv("C:\\Users\\Harsh Verma\\Documents\\Panda\\annual.csv",header=None, prefix="col")
csv_7

TypeError: read_csv() got an unexpected keyword argument 'prefix'

In [47]:
csv_7=pd.read_csv("C:\\Users\\Harsh Verma\\Documents\\Panda\\annual.csv",dtype={"Value":"float"})
csv_7

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H01,Total income,Financial performance,54462.0,ANZSIC06 division A
1,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H04,Sales of goods and services,Financial performance,51472.0,ANZSIC06 division A
2,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H05,"Interest, dividends and donations",Financial performance,893.0,ANZSIC06 division A
3,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H06,"Government funding, grants and subsidies",Financial performance,15.0,ANZSIC06 division A
4,2023,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H07,Non-operating income,Financial performance,2081.0,ANZSIC06 division A
...,...,...,...,...,...,...,...,...,...,...
93,2023,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H05,"Interest, dividends and donations",Financial performance,222.0,ANZSIC06 groups A014 and A015
94,2023,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H07,Non-operating income,Financial performance,680.0,ANZSIC06 groups A014 and A015
95,2023,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H08,Total expenditure,Financial performance,11627.0,ANZSIC06 groups A014 and A015
96,2023,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H09,Interest and donations,Financial performance,910.0,ANZSIC06 groups A014 and A015
97,2023,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H10,Indirect taxes,Financial performance,204.0,ANZSIC06 groups A014 and A015